
# This file is used to configure and run Collabora CODE using Docker Compose.
version: "3.6"
services:
  libreoffice-app:
    image: collabora/code:6.4.8.4
    container_name: libreoffice-app
    expose:
      - 9980
    ports:
      - "9980:9980"
    environment:
      - username=admin
      - password=adminadmin
    restart: always